<a href="https://colab.research.google.com/github/AmirRazer/G-Colab/blob/main/pengenalan_python_kampus_merdeka_bacth_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Day 1

##lestPractic
Hari ini kita akan belajar mengenai tipe data di python


### Data Types Python

    > Text Type:	str
    > Numeric Types:	int, float, complex
    > Sequence Types:	list, tuple, set, range
    > Mapping Type:	dict
    > Set Types:	set, frozenset
    > Boolean Type:	bool
    > Binary Types:	bytes, bytearray, memoryview
    > None Type:	NoneType

    

### Variable

- Variables are containers for storing data values.
- Python has no command for declaring a variable.

|Example|Data Type|
|:-|-:|
|x = "Halo! Teman-teman"|str|
|x = 22|int|
|x = 4.5|float|
|x = 1j|complex|
|x = ["alpukat", "durian", "mangga"]|list|
|x = ("alpukat", "durian", "mangga")|tuple|
|x = range(5)|range|
|x = {"nama" : "Angga", "Jurusan" : "Matematika"}|dict|
|x = {"alupkat", "durian", "mangga"}|set|
|x = frozenset({"alpukat", "durian", "mangga"})|frozenset|
|x = False/True|bool|
|x = b"Halo"|bytes|
|x = bytearray(4)|bytearray|
|x = memoryview(bytes(4))|memoryview|
|x = None|NoneType|


### Python Assignment Operators
`Assignment operators are used to assign values to variables:`

|Operator|	Example|	Same As|
|:-|:-|-:|
|=|	x = 5|	x = 5|
|+=|	x += 3|	x = x + 3|
|-=|	x -= 3|	x = x - 3|
|*=|	x *= 3|	x = x * 3|
|/=|	x /= 3|	x = x / 3|
|%=|	x %= 3|	x = x % 3|
|//=|	x //= 3|	x = x // 3|
|**=|	x **= 3|	x = x ** 3|
|&=|	x &= 3|	x = x & 3|
|^=|	x ^= 3|	x = x ^ 3|
|>>=|	x >>= 3|	x = x >> 3|
|<<=|	x <<= 3|	x = x << 3|

In [ ]:
#example of variablle
#example of using print with smicolon(;)

x = 22
y = "Hello world"
z =4,56

print(x)
print(y)
print(z)
print(x),print(y),print(z)



22
Hello world
(4, 56)
22
Hello world
(4, 56)


(None, None, None)

In [ ]:
#example of declare variable with coma(,)
#Example of using print with comma (,)
a,b =20,"hello"

print(a)
print(b)
print(type(a),type(b)) #cara cek tipe data

20
hello
<class 'int'> <class 'str'>


In [ ]:
x = '"amir"'

print(x)
print(type(x))

"amir"
<class 'str'>


In [ ]:
r=s=t= "Amir mahmud" #penyamaan 1 object dengan variabel
print(s)

Amir mahmud


In [ ]:
a,b,c,d,e,f="python" # baca perkarakter
print(a,b)
print(e,f)

p y
o n


In [ ]:
m=str(4) #maka 4 sebagai '4'
n=int(4) #maka 4 sebagai integer
o=float(4) #angka 4 sebagai 4.0

print(type(m));print(type(n));print(type(o));



<class 'str'>
<class 'int'>
<class 'float'>


##hands on


In [ ]:


x = 1
 # hardcode your test data here
x = float(x)

# Calculate the equation
y = 3*x**3 - 2*x**2 + 3*x - 1

print("y =", y)


y = 3.0


In [ ]:
x = 0
x = 1
x = -1
print(x)

-1


#Day 2 rabu-20-03-2024


##Matrikulasi


In [ ]:
for i in range(3):
  print(i)

0
1
2


##Lest Practic

### Range In python

In [ ]:
x=range(6) #0<= x<6
print(x)
for n in x:
  print(n)

range(0, 6)
0
1
2
3
4
5


***range(n) := 0 <= x < n*** <br>
for example: range(5) means 0 <= x < 5

#### Syntax function range
`range(start, stop, step)` -> syntax Range, default step 1 if not define

In [ ]:
x = range(1,10,2)
for n in x:
  print(n)

1
3
5
7
9


- ***INT*** or integer, is a whole number, positive or negative, without decimals, of unlimited length.

- ***FLOAT*** or "floating point number" is a number, positive or negative, containing one or more decimals.

- ***COMPLEX*** numbers are written with a "j" as the imaginary part

In [ ]:
a = 100 #a adalah integer
b = 13.8976 #b adalah bilangan desimal
c =5j #c adalah bilangan kompleks

print(a,type(a))
print(b,type(b))
print(c,type(c))


100 <class 'int'>
13.8976 <class 'float'>
5j <class 'complex'>


In [ ]:
x = 10 #integer
y = 15.5 #float

#konvert/casting dari integer ke float
p = float(x)

#Konvert/casting dari float ke integer
q=int(y)

r= complex(x)

print("ini adalah x",x,"dengan type",type(x))
print("ini adalah y",y,"dengan type",type(y))
print("ini adalah p",p,"dengan type",type(p))
print("ini adalah q",q,"dengan type",type(q))
print("ini adalah r",r,"dengan type",type(r))



ini adalah x 10 dengan type <class 'int'>
ini adalah y 15.5 dengan type <class 'float'>
ini adalah p 10.0 dengan type <class 'float'>
ini adalah q 15 dengan type <class 'int'>
ini adalah r (10+0j) dengan type <class 'complex'>


### python aritmatic operator
|Example|Data Type|
|:-|-:|
|x = "Halo! Teman-teman"|str|
|x = 22|int|
|x = 4.5|float|
|x = 1j|complex|
|x = ["alpukat", "durian", "mangga"]|list|
|x = ("alpukat", "durian", "mangga")|tuple|
|x = range(5)|range|
|x = {"nama" : "Angga", "Jurusan" : "Matematika"}|dict|
|x = {"alupkat", "durian", "mangga"}|set|
|x = frozenset({"alpukat", "durian", "mangga"})|frozenset|
|x = False/True|bool|
|x = b"Halo"|bytes|
|x = bytearray(4)|bytearray|
|x = memoryview(bytes(4))|memoryview|
|x = None|NoneType|


`Arithmetic operators are used with numeric values to perform common mathematical operations`
|Operator|	Name|	Example|
|:-|:-|-:|
|+|	Addition|	x + y|
|-|	Subtraction|	x - y|
|*|	Multiplication|	x * y|
|/|	Division|	x / y|
|%|	Modulus|	x % y|
|**|	Exponentiation|	x ** y|
|//|	Floor division|	x // y|

In [ ]:
x= 6 ; y =20
print("Adidition",x+y)
print("Subtraction",x-y)
print("Multiplication",x*y)
print("Division",x/y)
print("Modulus",x%y)
print("Exponettion",x**y)#pangkat
print("Flor Division",x//y)#pembagian dengan pembulatan



Adidition 26
Subtraction -14
Multiplication 120
Division 0.3
Modulus 6
Exponettion 3656158440062976
Flor Division 0


###python asigment operaor
|Operator|	Example|	Same As|
|:-|:-|-:|
|=|	x = 5|	x = 5|
|+=|	x += 3|	x = x + 3|
|-=|	x -= 3|	x = x - 3|
|*=|	x *= 3|	x = x * 3|
|/=|	x /= 3|	x = x / 3|
|%=|	x %= 3|	x = x % 3|
|//=|	x //= 3|	x = x // 3|
|**=|	x **= 3|	x = x ** 3|
|&=|	x &= 3|	x = x & 3|
|^=|	x ^= 3|	x = x ^ 3|
|>>=|	x >>= 3|	x = x >> 3|
|<<=|	x <<= 3|	x = x << 3|

In [ ]:
#Membuat paragraf
paragraf = '''Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.'''
print(paragraf)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


In [ ]:
nama="Arya"

print(nama[1:3])#titik dua disini mendifisikan sebagai range

ry


In [ ]:
data="Latihan Python"
nilai = "75"
spasi= ""
nama='amir'
nilai1 = 555

print(data.isnumeric())#cek apakah tipe data numeric pada string
print(nilai.isnumeric())#cek apakah tipe nilai numeric pada string
print(data)



False
True
Latihan Python


In [ ]:
variabel = "Training Python"
print(variabel.find("n"))
print(variabel.find("n",7))

4
14


In [ ]:
number="123"
number1="ab"

print(number.zfill(10))#membuat karakter dengan length 10
print(number1.zfill(5))#membuat karakter dengan length 5

0000000123
000ab


In [ ]:
titile="latihan"
title1="training"

print(titile.center(10,"-"))
print(title1.center(10,"-"))
print(titile.replace('a','x'))#menganti karakter

-latihan--
-training-
lxtihxn


##Matrikulasi

In [ ]:
a = 'PYTHON'
for i in range(len(a)):
  print(i,a[i])

0 P
1 Y
2 T
3 H
4 O
5 N


In [ ]:
for i in range(3):
  print(f"Outer loop {i}")
  for j in range(2):
    print(f"Inner loop{j}")

Outer loop 0
Inner loop0
Inner loop1
Outer loop 1
Inner loop0
Inner loop1
Outer loop 2
Inner loop0
Inner loop1


### latihan 1
### Latihan 1
Tulis rumus ini dalam kode program:<br/> $c=\sqrt{a^2+b^2}$

carilah nilai C dengan nilai a = 3, dan b = 4

In [ ]:
def hitung_c(a, b):
    c = (a**2 + b**2)**0.5
    return c

# Contoh penggunaan
a = 3
b = 4
hasil = hitung_c(a, b)
print("Nilai c adalah:", hasil)

#
import math
a = 3
b = 4
c = math.sqrt(a**2 + b**2)
print("Nilai c adalah:", c)

a = 3
b = 4
c =  ((3 ** 2) + (4 ** 2)) ** 0.5
print(c)

Nilai c adalah: 5.0
Nilai c adalah: 5.0
5.0


### Latiihan 2

<b>Cerita Pendek:</b>

Suatu waktu di kebun apel, Guntur memiliki 3 apel, Icha memiliki 5 apel dan Ratna memiliki 6 Apel. mereka sangat bahagia dan hidup lama. selesai.

Tugas Anda
- buat variabe : `Guntur`, `Icha` dan `Ratna`
- isi nilai sesuai dengan jumlah apel yang mereka miliki
- cetak nama variabel dan jumlah apel setiap variabel dalam 1 baris, pisahkan dengan koma
- buat variabel baru dengan nama `totalApel` yang berisi penjumlahan seluruh apel yang mereka miliki
- coba otak atik code dengan membuat variable baru, diisi dengan nilai lain, dan dihitung dengan operator aritmetik lainnya

In [ ]:
Guntur = 3
Icha = 5
Ratna = 6
print (Guntur, Icha, Ratna)
total = Guntur + Icha + Ratna
print(total)

3 5 6
14


### Latihan 3

Mil dan kilometer adalah satuan panjang

1 mil memiliki panjang sekitar 1.61 kilometer, buatlah program konversi di bawah ini
- mil ke kilometer;
- kilometer to mil.
jangan ganti apapun terhadap kode yang sudah ada. tulis kodemu pada tanda ###, kemudian hapus tanda tersebut. Uji kode Anda dengan data yang kami sajikan dalam source code


In [ ]:
kilometer = 12.25
mil = 7.38
# Konversi mil ke kilometer
mil_ke_kilometer = mil * 1.61

# Konversi kilometer ke mil
kilometer_ke_mil = kilometer / 1.61

print(mil, "1 mil adalah", round(mil_ke_kilometer, 2), "kilometer")
print(kilometer, "1 kilometer adalah", round(kilometer_ke_mil, 2), "mil")

7.38 1 mil adalah 11.88 kilometer
12.25 1 kilometer adalah 7.61 mil


### Latihan 4
Kerjakan rumus berikut:

$$\frac{1}{x+\frac{1}{x+\frac{1}{x+\frac{1}{x}}}}$$

input/output yang diharapkan
```python
x = 1
y = 0.6000000000000001

x = 10
y = 0.09901951266867294

In [ ]:
# Fungsi untuk menghitung nilai dari rumus yang diberikan
def hitung_rumus(x):
    return 1 / (x + 1 / (x + 1 / (x + 1 / x)))

# Test cases
x = 1
y = hitung_rumus(x)
print("x =", x)
print("y =", y)

x = 10
y = hitung_rumus(x)
print("x =", x)
print("y =", y)


x = 1
y = 0.6000000000000001
x = 10
y = 0.09901951266867294


In [ ]:
celcius = 25

kelvin = celcius + 273.15
print("Suhu di Jakarta saat ini dalam Kelvin:", kelvin)

fahrenheit = (celcius * 9/5) + 32
print("Suhu di Jakarta saat ini dalam Fahrenheit:", fahrenheit)

reamur = celcius * 4/5
print("Suhu di Jakarta saat ini dalam Reamur:", reamur)

Suhu di Jakarta saat ini dalam Kelvin: 298.15
Suhu di Jakarta saat ini dalam Fahrenheit: 77.0
Suhu di Jakarta saat ini dalam Reamur: 20.0


In [ ]:
#salah
detik = 753000

jam = detik /24
menit = jam / 60
sisa_detik = menit/60

print (detik,"detik Dirubah ke konversi waktu",jam,"jam",menit,"menit",sisa_detik,"dettik")

753000 detik Dirubah ke konversi waktu 31375.0 jam 522.9166666666666 menit 8.715277777777777 dettik


In [ ]:
detik = 753000

jam = detik // 3600
menit = detik // 60
sisa_detik = detik % 60

print(detik, "detik Dirubah ke konversi waktu=", jam, " jam ", menit, " menit", sisa_detik, " detik ")

753000 detik Dirubah ke konversi waktu= 209  jam  12550  menit 0  detik 


#day 3


In [ ]:
import string

kode = 'aiueo'
kode2 = '12345'
kalimat='Latihan Pytho'
transfrom=kalimat.maketrans(kode,kode2)
print(kalimat)
print(transfrom)
print(kalimat.translate(transfrom))

Latihan Pytho
{97: 49, 105: 50, 117: 51, 101: 52, 111: 53}
L1t2h1n Pyth5


In [ ]:
usia = 21
text = 'Nama saya Amir Mahmud, umur saya{}'
print(text.format(usia))

Nama saya Amir Mahmud, umur saya21


In [ ]:
qty = 6
produk_no=567
harga=100000
order='saya mamu membeli {} buah produk{} dengan harga{}'
print(order.format(qty,produk_no,harga))

saya mamu membeli 6 buah produk567 dengan harga100000


In [ ]:
qty = 6
produk_no=567
harga=100000
order='saya mamu membeli {2} buah produk{1} dengan harga{0}'
print(order.format(harga,qty,produk_no))

saya mamu membeli 567 buah produk6 dengan harga100000


## string method
`Python has a set of built-in methods that you can use on strings.` <br>
**Note:** All string methods return new values. They do not change the original string.

    - capitalize():	Converts the first character to upper case
    - casefold():	Converts string into lower case
    - center():	Returns a centered string
    - count():	Returns the number of times a specified value occurs in a string
    - encode():	Returns an encoded version of the string
    - endswith():	Returns true if the string ends with the specified value
    - expandtabs():	Sets the tab size of the string
    - find():	Searches the string for a specified value and returns the position of where it was found
    - format():	Formats specified values in a string
    - format_map():	Formats specified values in a string
    - index():	Searches the string for a specified value and returns the position of where it was found`Python has a set of built-in methods that you can use on strings.` <br>

    - capitalize():	Converts the first character to upper case
    - casefold():	Converts string into lower case
    - center():	Returns a centered string
    - count():	Returns the number of times a specified value occurs in a string
    - encode():	Returns an encoded version of the string
    - endswith():	Returns true if the string ends with the specified value
    - expandtabs():	Sets the tab size of the string
    - find():	Searches the string for a specified value and returns the position of where it was found
    - format():	Formats specified values in a string
    - format_map():	Formats specified values in a string
    - index():	Searches the string for a specified value and returns the position of where it was found
    - isalnum():	Returns True if all characters in the string are alphanumeric
    - isalpha():	Returns True if all characters in the string are in the alphabet
    - isdecimal():	Returns True if all characters in the string are decimals
    - isdigit():	Returns True if all characters in the string are digits
    - isidentifier():	Returns True if the string is an identifier
    - islower():	Returns True if all characters in the string are lower case
    - isnumeric():	Returns True if all characters in the string are numeric
    - isprintable():	Returns True if all characters in the string are printable
    - isspace():	Returns True if all characters in the string are whitespaces
    - istitle():	Returns True if the string follows the rules of a title
    - isupper():	Returns True if all characters in the string are upper case
    - join():	Joins the elements of an iterable to the end of the string
    - ljust():	Returns a left justified version of the string
    - lower():	Converts a string into lower case
    - lstrip():	Returns a left trim version of the string
    - maketrans():	Returns a translation table to be used in translations
    - partition():	Returns a tuple where the string is parted into three parts
    - replace():	Returns a string where a specified value is replaced with a specified value
    - rfind():	Searches the string for a specified value and returns the last position of where it was found
    - rindex():	Searches the string for a specified value and returns the last position of where it was found

## Boolean

Booleans represent one of two values: ***True*** or ***False***.

### Python Comparison Operators
`Comparison operators are used to compare two values:`

|Operator |Name| Example|
|:-|:-|-:|
|==|Equal|	x == y|
|!=|Not equal|	x != y|
|>| Greater than|	x > y|
|<|Less than|	x < y|
|>=	|Greater than or equal to|	x >= y|
|<=	|Less than or equal to|	x <= y|

In [ ]:
print(10 < 9)
print(10 == 9)
print(10 > 9)

False
False
True


In [ ]:
# contoh sederhana menggunakan if else

a = 5
b = 7

if b > a:
  print('B lebih besar dari a')
else:
  print('B lebih kecil dari a')

B lebih besar dari a


In [ ]:
#beberapa case dengan output boolean TRUE

print(bool('Amir'))
print(bool(21))
print(bool(['manga','jeruk','apel']))

True
True
True


In [ ]:
#beberapa case dengan output boolean FALSE

print(bool(False))
print(bool(None))
print(bool())
print(bool(''))
print(bool([]))
print(bool({}))
print(bool(()))

False
False
False
False
False
False
False


### none type

- The None keyword is used to define a null value, or no value at all.
- None is not the same as 0, False, or an empty string. None is a data type of its own (NoneType) and only None can be None.`

In [ ]:
a = None
b = 0
c = False
d = ''

print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'NoneType'>
<class 'int'>
<class 'bool'>
<class 'str'>


In [ ]:
x = None

if x is True:
  print("Do you think None is true?")
elif x is False:
  print("Do you think None is False")
else:
  print("None is not True Or False,None Is Just None")

None is not True Or False,None Is Just None


### Python Colection(Array)

There are four collection data types in the Python programming language:

- **List** is a collection which is ordered and changeable. Allows duplicate members.
- **Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
- **Set** is a collection which is unordered, unchangeable#, and unindexed. No duplicate members.
- **Dictionary** is a collection which is ordered## and changeable. No duplicate members.

*# Set items are unchangeable, but you can remove and/or add items whenever you like.* <br>
*## As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered*

#### List


`Lists are used to store multiple items in a single variable.`

`Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.`

In [ ]:
data = [75,"Nila9",80.6] #Kurung siku digunakan untuk tipe data list dan bisa berisi beberapa tipe data
print(data)
print(type(data))
print(data[0]) #Membada data pertama dari list yang ada(Index 0)
print(len(data)) #Untuk menghitung jumlah value yang ada di list

[75, 'Nila9', 80.6]
<class 'list'>
75
3


##### List Item

In [ ]:
nilai = [95,70,75,65,11]
print(nilai[0]) #output berupa nilai pertama yang ada di list(index 0)
print(nilai[0:2])#output berupa nilai pertama dan kedua yang ada di list(index 0 dan 1)
print(nilai[0:])#output berupa nilai pertama sampai nilai terakhir
print(nilai[:2])#output nilai pertama sampai batas nilai ke satu(index 0 sampai 2)
print(nilai * 3)#output nilia yang diulang sebanyak 3 kali

nilai[4] = 120
print(nilai)
nilaibaru=nilai+[90,25,105]#menambahkan value dalam list lebih dari satu
print(nilaibaru)
nilai.append(900)#menambahkan sebuah value dalam list
print(nilai)

print('nilai baru: ', nilaibaru)
nilaibaru.sort()
print('nilai baru setelah di sort', nilaibaru)
nilaibaru.reverse()
print('nillai baru seteleh di reverse', nilaibaru)


95
[95, 70]
[95, 70, 75, 65, 11]
[95, 70]
[95, 70, 75, 65, 11, 95, 70, 75, 65, 11, 95, 70, 75, 65, 11]
[95, 70, 75, 65, 120]
[95, 70, 75, 65, 120, 90, 25, 105]
[95, 70, 75, 65, 120, 900]
nilai baru:  [95, 70, 75, 65, 120, 90, 25, 105]
nilai baru setelah di sort [25, 65, 70, 75, 90, 95, 105, 120]
nillai baru seteleh di reverse [120, 105, 95, 90, 75, 70, 65, 25]


In [ ]:
isi=['Sample','Training','latihan']
isi.sort() #mengurutkan sesuai abdjat
print(isi)
nilai=[50,60,70]
nilai.sort(reverse=True)#mengurutkan dari besar ke kecil(sama kaya. reverse)
print(nilai)

['Sample', 'Training', 'latihan']
[70, 60, 50]


In [ ]:
kata = ['abc','ABD','aBe','aBd']
kata.sort()
print(kata)
#fungsi key berguna untuk mengurutkan karakter bds sifat yang digunakan
kata.sort(key=str.lower)
print(kata)

['ABD', 'aBd', 'aBe', 'abc']
['abc', 'ABD', 'aBd', 'aBe']


In [ ]:
angka=[90,20,76,89,34,57]
angka.append(78)
print(angka)
angka.insert(2,75)
print('angka insert',angka)#menyisipkan angka sesuai yang diingginkan
angka[5]=20
print(angka)
print('Angka 20 ada sebanyak: ', angka.count(20))
angka.remove(20)
print(angka)
angkabaru= angka + [20,20]
print(angkabaru)
angkabaru.clear()
print(angkabaru)

[90, 20, 76, 89, 34, 57, 78]
angka insert [90, 20, 75, 76, 89, 34, 57, 78]
[90, 20, 75, 76, 89, 20, 57, 78]
Angka 20 ada sebanyak:  2
[90, 75, 76, 89, 20, 57, 78]
[90, 75, 76, 89, 20, 57, 78, 20, 20]
[]


In [ ]:
data = ["Sample",[90,22,34,75],75.75]
print(data[0])
print(data[1])
print(data[1][2]) #memnculkan data pada list dalam list (multi dimentional array)
print(data[1][3])

Sample
[90, 22, 34, 75]
34
75


In [ ]:
judul = "Latihan untuk Training Python"
print(judul.split(" ")) #Melakukan split karakter terhadap variabel lalu membuat tipe data string menjadi bentuk list

['Latihan', 'untuk', 'Training', 'Python']


##### List Method
Method	Description
    
    - append()	Adds an element at the end of the list
    - clear()	Removes all the elements from the list
    - copy()	Returns a copy of the list
    - count()	Returns the number of elements with the specified value
    - extend()	Add the elements of a list (or any iterable), to the end of the current list
    - index()	Returns the index of the first element with the specified value
    - insert()	Adds an element at the specified position
    - pop()	Removes the element at the specified position
    - remove()	Removes the item with the specified value
    - reverse()	Reverses the order of the list
    - sort()	Sorts the list

#day 4 Senin 25-03-2024

## Lest practic

### tuple
`Tuples are used to store multiple items in a single variable.`

`Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.`

`A tuple is a collection which is ordered and unchangeable.`

`Tuples are written with round brackets. "( )"`

In [ ]:
data = (4,60,25,39,18)
data1= {4,60,25,39,18}
data2= [4,60,25,39,18]

print(data)
print(len(data))
print(type(data))
print(type(data1))
print(type(data2))



(4, 60, 25, 39, 18)
5
<class 'tuple'>
<class 'set'>
<class 'list'>


In [ ]:
#print(data)
#data[2]=20

In [ ]:
thistuple1=("apple")
print(type(thistuple1))


thistuple=("apple","mangga")
print(type(thistuple))

<class 'str'>
<class 'tuple'>


In [ ]:
data=(1,2,3,4,5)
print(data+(6,7,8))

month=("jan","Feb","Mar")
print(month+("Apr","May","Jun"))

(1, 2, 3, 4, 5, 6, 7, 8)
('jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun')


In [ ]:
isidata=("latihan","python","hari","keempat")
print(type(isidata))
separator="-"
hasil=separator.join(isidata)#mengabungkan elemen tuple sekaligus meruubah tipe datanya menjadi string
print(hasil)
print(type(hasil))

<class 'tuple'>
latihan-python-hari-keempat
<class 'str'>


In [ ]:
data=("abc",30,True,34.5,"60")#element tuple bisa berbagai macam tipe data
print(data)
print(type(data))

('abc', 30, True, 34.5, '60')
<class 'tuple'>


In [ ]:
thistuple=tuple(("Apple","Mango","Cherry"))#mngubah tipe data variabel
print(thistuple)
print(type(thistuple))

('Apple', 'Mango', 'Cherry')
<class 'tuple'>


In [ ]:
thistuple=tuple(("apple"))
print(thistuple)

('a', 'p', 'p', 'l', 'e')


In [ ]:
thistuple=tuple("apple")
print(thistuple)

('a', 'p', 'p', 'l', 'e')


In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-1])
print(thistuple[2:5])


mango
('cherry', 'orange', 'kiwi')


In [ ]:
#update tuple
x=("apple","Banana","Manggo")
y=list(x)

y[1]="Kiwi"
x=tuple(y)

print(x)
print(type(x))

('apple', 'Kiwi', 'Manggo')
<class 'tuple'>


In [ ]:
x=("apple","Banana","Manggo")
x.count('apple')

1

##Set
`Sets are used to store multiple items in a single variable.`

`Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage.`

`A set is a collection which is unordered, unchangeable*, and unindexed.`

`Set are written with curly brackets. "{ }"`

*Note: Set items are unchangeable, but you can remove items and add new items.*

In [ ]:
thisset={1,3,4} #Tipe data set menggunakan tanda kurung kurawal{}
print(thisset)
print(type(thisset))

{1, 3, 4}
<class 'set'>


In [ ]:
thisset={1,1,2,3,4,5}# gabisa duplicate value
print(thisset)
print(len(thisset))

{1, 2, 3, 4, 5}
5


In [ ]:
set1={'abc',60,True,60.5,"60"}
print(type(set1))

<class 'set'>


In [ ]:
data=set(("apple","Banana")) #mengubah tipe data tuple menjadi set
print(data)
print(type(data))

{'Banana', 'apple'}
<class 'set'>


In [ ]:
data={'abc',60,True,60.5,"60"}
print(data)
#print(data[1]) #ternyata tidak bisa

{True, 60, 60.5, '60', 'abc'}


- You cannot access items in a set by referring to an index or a key.
- But you can loop through the set items using a for loop, or ask if a specified value is present in a set, by using the in keyword.

In [ ]:
thisset={"apple","Banana","manggo"}

for x in thisset:
  print(x)


manggo
Banana
apple


In [ ]:
thisset={"apple","Banana","manggo"}

for x in thisset:
  print(x, end=" ")

manggo Banana apple 

In [ ]:
this={"apple","Banana","Manggo"}
print("banana" in this)

False


In [ ]:
this={"apple","Banana","Manggo"}
print("Banana" in this)

True


In [ ]:
this={"apple","Banan","Manggo"}
this.add("Orange")
print(this)

{'Orange', 'Manggo', 'Banan', 'apple'}


In [ ]:
thisset={"apple","Banna","Mango"}
buahlain={"Orange","Avocado"}
lagi={"pear","Melon"}
thisset.update(buahlain,lagi) #untik gabungin 2 set
print(thisset)

{'Mango', 'Orange', 'Melon', 'pear', 'Banna', 'apple', 'Avocado'}


In [ ]:
thisset={"apple","Banna","Mango"}
buah_list=["Orange","Avocado"]
thisset.update(buah_list) #untik gabungin 2 set
print(thisset)

{'Mango', 'Banna', 'Orange', 'apple', 'Avocado'}


In [ ]:
thisset={"apple","banna","chery"}
thisset.remove("banna")
print(thisset)

{'chery', 'apple'}


In [ ]:
thisset={"apple","banna","chery"}
thisset.discard("bannaa") #kalo value gak ada ga eror
print(thisset)

{'chery', 'banna', 'apple'}


In [ ]:
thisset = {"apple", "banana", "cherry"}
x = thisset.pop() #mendefinisikan ke variabel nilai yang di-pop (yang terhapus)
print(x) #nampilin nilai yg terhapus
print(type(x))
print(thisset) #nampilin set setelah ada nilai yg dihapus

cherry
<class 'str'>
{'banana', 'apple'}


In [ ]:
thisset={"apple","banana","cherry"}
thisset.clear()
print(thisset)

set()


In [ ]:
# thisset = {"apple","banana","Chery"}
# del thisset
# print(thisset)

#Day 5 rabu 27 03 2024

## Let's Practice

### Dictionary

`Dictionaries are used to store data values in key:value pairs.`

`A dictionary is a collection which is ordered*, changeable and do not allow duplicates.`

In [ ]:
isi = {'nilai' : 75, 'diskripsi':'Testing','hsil': 50,}
print(isi)
print(type(isi))
print(isi.keys())#melihat key dalam dictionary
print(isi.values())#melihat value dalam dictinoary
print(isi.items())#untuk melihat elemen dalam dictionary berupa key value
print(len(isi))

{'nilai': 75, 'diskripsi': 'Testing', 'hsil': 50}
<class 'dict'>
dict_keys(['nilai', 'diskripsi', 'hsil'])
dict_values([75, 'Testing', 50])
dict_items([('nilai', 75), ('diskripsi', 'Testing'), ('hsil', 50)])
3


In [ ]:
#untuk melihat value berdasarkan key yang di pilih
print(isi['diskripsi'])
x = isi.get('deskripsi')
print(x)

Testing
None


In [ ]:
isi = {'nilai' : 75, 'diskripsi':'Testing','hasil': 50,'hasil':100}
print(isi)
print(type(isi))

{'nilai': 75, 'diskripsi': 'Testing', 'hasil': 100}
<class 'dict'>


In [ ]:
isi[500]='sample' #menambahkan value baru dan memperlihatkan ahwa key gak harus selalu string
print(isi)

{'nilai': 75, 'diskripsi': 'Testing', 'hasil': 100, 500: 'sample'}


In [ ]:
car = {
    'brand' : 'Ford',
    'model' : 'Mustang',
    'year' : 1964
}
x = car.keys()
print(x) #sebelum dai tambahkan value baru

car['color'] = 'white'

print(x) #setelah di tambahkan value baru
print(car)

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'white'}


In [ ]:
biodata = {}#membuat dictionary dengan lebih dinamis mengnakan empty dictionary
biodata['nama'] = 'Amir Mahmud'
biodata['email'] = 'amirmahmoed003@gmail.com'
biodata['usia'] = 21
print(biodata)
biodata['usia'] = 20 #update value dari suatu key
print(biodata)

{'nama': 'Amir Mahmud', 'email': 'amirmahmoed003@gmail.com', 'usia': 21}
{'nama': 'Amir Mahmud', 'email': 'amirmahmoed003@gmail.com', 'usia': 20}


In [ ]:
x =set('tri')
print(x)
y=set([2,3,1,1])
print(y)

{'t', 'i', 'r'}
{1, 2, 3}


In [ ]:
z = dict(zip(x,y))
print(z)
print(type(z))

{'t': 1, 'i': 2, 'r': 3}
<class 'dict'>


In [ ]:
a = ['a','b']
b = [1,2]
c=dict(zip(a,b))
print(c)

{'a': 1, 'b': 2}


### Dictionary Method

Method	Description

    - clear()	Removes all the elements from the dictionary
    - copy()	Returns a copy of the dictionary
    - fromkeys()	Returns a dictionary with the specified keys and value
    - get()	Returns the value of the specified key
    - items()	Returns a list containing a tuple for each key value pair
    - keys()	Returns a list containing the dictionary's keys
    - pop()	Removes the element with the specified key
    - popitem()	Removes the last inserted key-value pair
    - setdefault()	Returns the value of the specified key. If the key does not exist: insert the key, with the specified value
    - update()	Updates the dictionary with the specified key-value pairs
    - values()	Returns a list of all the values in the dictionary

### Block Statement

A block statement, or compound statement, lets you group any number of data definitions, declarations, and statements into one statement

#### If Else Statement

The if-else statement is used to execute both the true part and the false part of a given condition

In [ ]:
a = 151

if a > 100:
  print('a is big number')
else:
  print('a is small number')

a is big number


In [ ]:
#4if else untuk 2 kondis terdefinisi

m = 100

if m < 100 : # kondisi 1
  print('small Number')
elif m > 100: # Kondisi 2
  print('medium number')
else: #kondisi lainya
  print('Big Number')

Big Number


In [ ]:
#if else dengan 2 kondisi, dan variabel yang didefinisikan memenuhi 2 kondisi tersebut
n = 150
if n < 100 : # kondisi 1
  print('small Number')
elif n > 150: # Kondisi 2
  print('medium number')
else: #kondisi lainya
  print('Big Number')

Big Number


In [ ]:
# if else untuk string
isi='mobil'

if 'm' in isi:
  print('terdapat huruf m')
else:
  print('tidak terdapat huruf m')

terdapat huruf m


In [ ]:
# if else untuk membandingkan 2 variable

bilangan1 = 35
bilangan2 = 20

if bilangan1 == bilangan2:
  print('bilangan sama')
if bilangan1 != bilangan2:
  print('bilangan beda')

bilangan beda


In [ ]:
x = -5
y = 0

if x <0 and y <0:
  print('x dan y bilangan negarif')
elif x < 0 and y >0:
  print('x bilangan negatif dan y bilangan positif')
elif x > 0 and y < 0:
  print('x bilangan positif dan y bilangan negatif')
elif x >0 and y>0:
  print('x dan y bilangan positif')
elif x==0 and y==0:
  print('keduanya 0')
else:
  print('salah satunya ada yang noll')

salah satunya ada yang noll


#### For statement

A control flow statement that is used to repeatedly execute a group of statements as long as the condition is satisfied

In [ ]:
for x in range(1,6):
  print(x)

1
2
3
4
5


In [ ]:
for x in range(2,11,2): #Kita tentukan batas awal dan akhir serta beda range yang di gunakan
  print(x)

2
4
6
8
10


In [ ]:
for x in range(1,10,-2): #Kita tentukan batas awal dan akhir serta beda range yang di gunakan
  print(x)

In [ ]:
#for untuk string
isi = 'training'

for x in isi:
  print(x)

t
r
a
i
n
i
n
g


In [ ]:
#for untuk list

data=['testing','sample','coba']

for x in data:
  print(x)

#mencetak indeks dan nilai secara bersama

for idx, x in enumerate(data):
  print(idx,x)

testing
sample
coba
0 testing
1 sample
2 coba


In [ ]:
buah=['apple','banan','mango']
warna=['red','yellow','green']

for buah,warna in zip(buah,warna):
  print(f"the color of {buah} is {warna}")


the color of apple is red
the color of banan is yellow
the color of mango is green


In [ ]:
#for pada dictionary, ngebaca key

member = {"nama":"someone","nilai":75,"kredit":15000} #untuk membaca key dict
print(member)

print(" ") #bertindak sebagai enter

for k in member:
    print(k)

print("\n")

for k in member:
    print(member[k])

print(" ")

for k in member:
  print(k, "=", member[k])

{'nama': 'someone', 'nilai': 75, 'kredit': 15000}
 
nama
nilai
kredit


someone
75
15000
 
nama = someone
nilai = 75
kredit = 15000


In [ ]:
#for pada dictionary, ngebaca key dan value

member = {"nama":"someone","nilai":75,"kredit":15000} #untuk membaca anggota list
print(member)
print(member.items())

print(" ")

for (k,v) in member.items(): #menggunakan hasil dari member.items
    print(k,"=",v)

{'nama': 'someone', 'nilai': 75, 'kredit': 15000}
dict_items([('nama', 'someone'), ('nilai', 75), ('kredit', 15000)])
 
nama = someone
nilai = 75
kredit = 15000


##Matrikulasi

In [ ]:
library = {
    'book' : {'Author' : ['Robert','Opet'],
              'judul': ['batman','Nuclear'],
              'tahun_terbit': [2019,2020,2]}
}

In [ ]:
library['book']['judul'][1]

'Nuclear'

In [ ]:
# Inisialisasi variabel untuk menyimpan informasi transaksi
transactions = []

# Inisialisasi variabel untuk total transaksi dan total pendapatan
total_transactions = 0
total_income = 0.0

# Dictionary untuk menyimpan jumlah penjualan setiap menu
menu_sales = {}

# List untuk menyimpan nama pelanggan pada transaksi pertama dan terakhir
first_customers = []
last_customers = []

# Contoh transaksi
transaction1 = {
    "customer_name": "John",
    "ordered_items": ["Kopi", "Kue Croissant"],
    "total_amount": 10.50
}
transactions.append(transaction1)
total_transactions += 1
total_income += transaction1["total_amount"]

# Update penjualan menu
for item in transaction1["ordered_items"]:
    menu_sales[item] = menu_sales.get(item, 0) + 1

# Menyimpan nama pelanggan transaksi pertama
first_customers.append((transaction1["customer_name"], transaction1["ordered_items"]))

# Menyimpan nama pelanggan transaksi terakhir
last_customers = [(transaction1["customer_name"], transaction1["ordered_items"])]

# Contoh transaksi lain
transaction2 = {
    "customer_name": "Alice",
    "ordered_items": ["Kopi"],
    "total_amount": 3.50
}
transactions.append(transaction2)
total_transactions += 1
total_income += transaction2["total_amount"]

for item in transaction2["ordered_items"]:
    menu_sales[item] = menu_sales.get(item, 0) + 1

last_customers = [(transaction2["customer_name"], transaction2["ordered_items"])]

# Contoh transaksi lainnya
transaction3 = {
    "customer_name": "Bob",
    "ordered_items": ["Es Teh"],
    "total_amount": 2.00
}
transactions.append(transaction3)
total_transactions += 1
total_income += transaction3["total_amount"]

for item in transaction3["ordered_items"]:
    menu_sales[item] = menu_sales.get(item, 0) + 1

last_customers = [(transaction3["customer_name"], transaction3["ordered_items"])]

# Menampilkan informasi pada akhir hari
print("Total Transaksi:", total_transactions)
print("Total Pendapatan:", total_income)
print("Penjualan Menu:", menu_sales)
print("Pelanggan Pertama:", first_customers)
print("Pelanggan Terakhir:", last_customers)


Total Transaksi: 3
Total Pendapatan: 16.0
Penjualan Menu: {'Kopi': 2, 'Kue Croissant': 1, 'Es Teh': 1}
Pelanggan Pertama: [('John', ['Kopi', 'Kue Croissant'])]
Pelanggan Terakhir: [('Bob', ['Es Teh'])]


#Day 6 kamis 28-03-2024

##Lest Practic

### Block Statment

In [ ]:
print('Membuat barisan bilangan ganjil atau genap')

print('\n Masukan nilai awal dan nilai akhir(nilai_awal < nilai akhir)')
nilai_awal=int(input('Nilai Awal: '))
nilai_akhir=int(input('Nilai Akhir: '))

print('''\nMau Barisan Bilangan apa
1.Ganjil
2.Genap''')
pilihan=int(input('1 atau 2?'))

print('\n')
if pilihan not in [1,2]:
  print('pilihan salah!')
else:
  for x in range(nilai_awal,nilai_akhir+1):
    if pilihan == 1 and x % 2 == 1:
      print(x,end=' ')
    elif pilihan == 2 and x % 2 == 0:
      print(x,end=' ')

Membuat barisan bilangan ganjil atau genap

 Masukan nilai awal dan nilai akhir(nilai_awal < nilai akhir)
Nilai Awal: 12
Nilai Akhir: 12

Mau Barisan Bilangan apa
1.Ganjil
2.Genap
1 atau 2?1




#### While statement

A while statement in python sets aside a block of code that is to be executed repeatedly until a condition is falsified.

In [ ]:
#while True:
#  print('Welcome to celerates training')

In [ ]:
angka = 0

while angka < 5:
  print('Welcome to celerates training')
  angka +=1

Welcome to celerates training
Welcome to celerates training
Welcome to celerates training
Welcome to celerates training
Welcome to celerates training


In [ ]:
angka = 1

while angka < 10:
  print('Bilangan ke :', angka)
  angka +=2 #syarat supaya berhenti
else: #while bisa ditambahin block else
  print('Loop diakhiri dengan bilangan: ',angka)

Bilangan ke : 1
Bilangan ke : 3
Bilangan ke : 5
Bilangan ke : 7
Bilangan ke : 9
Loop diakhiri dengan bilangan:  11


In [ ]:
import random

jawaban = random.randint(1,10)
tebakan = int(input('Pilih bilangan antara 1 - 10: '))

while tebakan != jawaban:
  tebakan=int(input('Salah woy! cobah pilih lagi 1-10'))
print('Selamat!Tebakan anda')

Pilih bilangan antara 1 - 10: 1
Salah woy! cobah pilih lagi 1-101
Salah woy! cobah pilih lagi 1-1012
Salah woy! cobah pilih lagi 1-103
Salah woy! cobah pilih lagi 1-104
Salah woy! cobah pilih lagi 1-105
Salah woy! cobah pilih lagi 1-106
Salah woy! cobah pilih lagi 1-107
Salah woy! cobah pilih lagi 1-108
Selamat!Tebakan anda


In [ ]:
import random as rd
answer = rd.randint(1, 100)
print("Tebak angka antara 1-100")
while True:
    guess = int(input("Tebakan: "))
    if guess == answer:
        print("Tebakan benar", guess)
        break
    elif guess < answer:
        print(guess, "Tebakan terlalu kecil")
    else:
        print(guess, "Tebakan terlalu besar")

Tebak angka antara 1-100
Tebakan: 12
12 Tebakan terlalu kecil
Tebakan: 4
4 Tebakan terlalu kecil
Tebakan: 44
44 Tebakan terlalu besar
Tebakan: 33
33 Tebakan terlalu besar
Tebakan: 22
22 Tebakan terlalu kecil
Tebakan: 26
26 Tebakan terlalu besar
Tebakan: 24
Tebakan benar 24


#### Execption Statement

An event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions

In [ ]:
#block exception handling
#run error namun masih bisa dijalankan
#block except bisa lebih satu
#block finally bisa ditambahkan tanpa syarat tertentu untuk menjalankan running
#kalo sukses try langsung ke finally
#jika error try ke except baru ke finally
a = 4
b = 'test'
#c = a + b
#print(c)
try:
  c = a + b
  print(c)
except Exception as error:
  print('Erorr: ', error)

Erorr:  unsupported operand type(s) for +: 'int' and 'str'


In [ ]:
a = 4
b = 'test'
#c = a + b
#print(c)
try:
  c = a + b
  print(c)
except Exception as error:
  print('Erorr: ', error)
finally:
  print('Done!')

Erorr:  unsupported operand type(s) for +: 'int' and 'str'
Done!


In [ ]:
isi=[1,2,3,4,5]
#print(isi[6])

try:
  print(isi[6])
except IndexError as a:
  print('Error: ',a)
except Exception as e:
  print('Error: ',e)
finally:
  print('Done!')

Error:  list index out of range
Done!


In [ ]:
isi=[1,2,3,4,5]
#print(isi[6])

try:
  print(isi['Test'])
except IndexError as a:
  print('No Data Available',a)
except Exception as e:
  print('Index Must be numerc ',e)
except Exception as b:
  print('error:',b)
finally:
  print('Done!')

Index Must be numerc  list indices must be integers or slices, not str
Done!


In [ ]:
while True:
  try:
    x=float(input('Masukan Bilangan Pertama: '))
    y=float(input('Masukan Bilangan Kedua: '))
    result=x/y
    print('Hasil Pembagianya adalah',result)
    break
  except ValueError:
    print('Anda harus masukan bilangan')
  except ZeroDivisionError:
    print('Bilangan kedua tidak boleh nol')
  except Exception as a:
    print('Error:',a)

Masukan Bilangan Pertama: 1
Masukan Bilangan Kedua: 3
Hasil Pembagianya adalah 0.3333333333333333


### Function

A function is a block of code which only runs when it is called

In [ ]:
def pesan(): #deklarasi untuk membuat function
  print('Welcome')
  return #harus ada dia sebagai akhiran dari fungsi def dan bisa sebagaipengembali nilai dari sebuah function

In [ ]:
pesan()

Welcome


In [ ]:
def perkalian(x,y):
  print(x*y)

In [ ]:
perkalian(2,7)

14


In [ ]:
def message(pesan):
  print(pesan)

In [ ]:
message('Selamat Datang') #jenis 1
message(pesan='Selamat datang') #jenis 2

Selamat Datang
Selamat datang


##matrikuasi


In [ ]:
menu_dict = {'soto':1000,
             'baso':5000}

In [ ]:
customer_name_list = []


# Day 7 Senin 01-04-2024

## Lest Practic

### Fuction Lanjutan

In [ ]:
def pembagian(x=1,y=1): #membuat default
  return x/y
print('Pembagian 20 dengan 3 adalah',pembagian(20,3 ))
pembagian()
pembagian(25)

Pembagian 20 dengan 3 adalah 6.666666666666667


25.0

In [ ]:
def nilai(x,y,z):
  return(x+y)/z
print(nilai(2,3,5))

1.0


In [ ]:
def jumlah(x,y,z):
  return x+y+z
print(jumlah("20",'35','27')) #kalo string, jadinya nyatuin

203527


In [ ]:
def add_number(x,y):
  result=x+y
  return result

num1= float(input("masukan nilai x: "))
num2= float(input('masukan nilai y: '))

sum=add_number(num1,num2)
print(sum)

masukan nilai x: 1
masukan nilai y: 1
2.0


In [ ]:
import math

def hitung_keliling(jari_jari):
  keliling=2*math.pi*jari_jari
  return keliling

def hitung_l(jari_jari):
  luas=math.pi*jari_jari*jari_jari
  return luas

r=float(input('Masukan panjang jari-jari lingkaran: '))

kll=hitung_keliling(r)
L=hitung_l(r)

print('keliling lingkaran adalah', kll)
print('Luas lingkaran adalah', r)


Masukan panjang jari-jari lingkaran: 1
keliling lingkaran adalah 6.283185307179586
Luas lingkaran adalah 1.0


In [ ]:
import math

def hitung_luas_permukaan(r, t):
    luas_permukaan = 2 * math.pi * r * (r + t)
    return luas_permukaan

def hitung_volume(r, t):
    volume = math.pi * r * r * t
    return volume

r = float(input('Masukan panjang jari-jari lingkaran alas tabung: '))
t = float(input('Masukan tinggi tabung: '))

luas_permukaan = hitung_luas_permukaan(r, t)
volume = hitung_volume(r, t)

print('Luas permukaan tabung adalah', luas_permukaan)
print('Volume tabung adalah', volume)


Masukan panjang jari-jari lingkaran alas tabung: 1
Masukan tinggi tabung: 1
Luas permukaan tabung adalah 12.566370614359172
Volume tabung adalah 3.141592653589793


In [ ]:
def jumlah(x,y):
  if isinstance(x,int) & isinstance(y,int):
    return x+y
  elif isinstance(x,str) & isinstance(y,str):
    if x.isdigit() & y.isdigit():
      return int(x) + int(y)
    else:
      return 'Sory, Number only'

print(jumlah('2','3'))
print(jumlah('2','3a'))
print(jumlah(2,3))
print(jumlah(2,4))




5
Sory, Number only
5
6


In [ ]:
def jumlah(x, y):
    if isinstance(x, int) and isinstance(y, int):
        return x + y
    elif isinstance(x, str) and isinstance(y, str):
        if x.isdigit() and y.isdigit():
            return int(x) + int(y)
        else:
            return 'Sorry, Number Only'
    elif isinstance(x, str) and isinstance(y, int):
        return 'Sorry, Number Only'
    elif isinstance(x, int) and isinstance(y, str):
        return 'Sorry, Number Only'
print(jumlah('2','3'))
print(jumlah('2','3a'))
print(jumlah(2,3))
print(jumlah(2,'4'))
print(jumlah('2',3))



5
Sorry, Number Only
5
Sorry, Number Only
Sorry, Number Only


In [ ]:
#membuat fungction untuk tipe data yang memiliki banyak nilai
def totaldata(nilai):
  total=0
  if isinstance(nilai,list) | isinstance(nilai,tuple):
    for value in nilai:
      total += value
  return total

print(totaldata([1,2,3,4,5,6,7,8,9,10]))

print(totaldata((1,2,3,4,5)))


55
15


### lambda


Lambda is a keyword in Python for defining the anonymous function

In [ ]:
perkalian=lambda x,y: x*y; #seperti variable tapi isinya function

print(perkalian(5,4))
print(perkalian(5,'a'))


20
aaaaa


### Class

A class is a code template for creating objects. Objects have member variables and have behaviour associated with them. In python a class is created by the keyword class

In [ ]:
class biodata:
  basicsalary = 500000

  def isidata(self, nama, telp):
    self.fullname = nama
    self.phone = telp

  def cetakdata(self):
    print('Full Name: ', self.fullname)
    print('Phone Number: ', self.phone)


In [ ]:
data = biodata()

data.isidata('Amir','12345678')
data.cetakdata()

Full Name:  Amir
Phone Number:  12345678


In [ ]:
data.email = 'amir@gmail.com' #untuk menambahkan properti
hasattr(data,'gender') #cek properti data
hasattr(data,'email')
setattr(data,'gendar','male')

In [ ]:
hasattr(data,'gender')

False

In [ ]:
hasattr(data,'email')

True

In [ ]:
print('nama',data.fullname)
print('nama',data.gendar)
print('nama',data.email)
print('nama',data.phone)
print('nama',data.basicsalary)





nama Amir
nama male
nama amir@gmail.com
nama 12345678
nama 500000


In [ ]:
class person:
  def info(self,nama):
    self.fullname=nama
    if hasattr(self,'title'):
      title=getattr(self,'title')
      self.pesan='Welcome, '+title+ ' '+ nama
    else:
      self.pesan='Welcone, '+nama

In [ ]:
p=person()
p.title='Mr. '
p.info('Amir')
p.pesan

'Welcome, Mr.  Amir'

In [ ]:
q=person()
q.info('gema')
q.pesan

'Welcone, gema'

## matrikullasi

#Day 8 rabu 03-04-2024

##Lest Practice



###Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

(Check Numpy Documentation for more: https://numpy.org/doc/stable/user/)

In [ ]:
import numpy as np


In [ ]:
a_list=[1.0,2.0,3.0,4.0,5.0]
print(a_list)
a_list.append(6) #Nambahin Nilai
print(a_list)
a_list.remove(6) #Ngapus nilai
print(a_list)
a_list[1]=7.0 #replace
print(a_list)

print(type(a_list))

[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 2.0, 3.0, 4.0, 5.0, 6]
[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 7.0, 3.0, 4.0, 5.0]
<class 'list'>


###Numpy mirip seperti list, tapi numpy  immutable (append, remove, insert)

##### 1D Array

In [ ]:
#1DArray

a_numpy=np.array(a_list)#mengubah bentuk list menjadi array 1D
print(a_numpy)
# a_numpy.append(5)
a_numpy[1]=2.0
print(a_numpy)

[1. 7. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [ ]:
#cek nilai di suatu indeks
a_numpy[2]

3.0

In [ ]:
#cek dimensi
a_numpy.shape

(5,)

######Multidimensi Array(Matriks = 2D)

- struktur data disebut sebagai ndarray (number of dimension dr array-nya)
- array bisa dibentuk menjadi dimensi yang lebih dari 2 tergantung pendefinisiannya
- sebuah array yang memiliki dimensi 2 disebut sbg matriks

In [ ]:
b_list=[1,2,3,4,5]
print(b_list)
print(len(b_list))

c_list=[[1,2,3,4,5]]
print(len(c_list))

[1, 2, 3, 4, 5]
5
1


In [ ]:
#cek shape ketika dibuat matriks dengan 1 baris list
c_numpy=np.array(c_list)
print(c_numpy)
print(type(c_numpy))
print(c_numpy.shape)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

print(a)
print(a[1][1])
print(type(a))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
5
<class 'list'>


In [ ]:
matriks_a = np.array(a)
print(matriks_a)
print(type(matriks_a))
print('ambil 1 array',matriks_a[2])#Ngambil 1 baris berdasarkan indeks
print('ambil suatu nilai di sebuah array: ',matriks_a[1,1]) #mengambil spesifik nilai dari matriks
print('ambil suatu nilai di sebuah array: ',matriks_a[2,1]) #mengambil spesifik nilai dari matriks
print(type(matriks_a))
print(matriks_a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
ambil 1 array [7 8 9]
ambil suatu nilai di sebuah array:  5
ambil suatu nilai di sebuah array:  8
<class 'numpy.ndarray'>
(4, 3)


In [ ]:
print('dimensi: ', matriks_a.ndim)#cek dimensi
print('ordo: ', matriks_a.shape)#cek ukuran
print('item: ', matriks_a.size)#cek total element

dimensi:  2
ordo:  (4, 3)
item:  12


In [ ]:
#membuat matriks 0

matriks_nol=np.zeros((4,2))
print(matriks_nol)

#membuat matriks 1
matriks_satu=np.ones((4,4))
print(matriks_satu)

#matriks identitas
matriks_identitas=np.eye((2))
print(matriks_identitas)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]


##### indexing numpy

In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print('\n')

#indexing 1 elemen
print(x[0,1])
#indexing 1 baris
print(x[1])
#indexing range
print('\n')
print(x[1:3])

#indexing matriks
print(x[1:3, 0:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2
[5 6 7 8]


[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6]
 [ 9 10]]


In [ ]:
#Output dijadikan matriks

y=np.array(x[1:3, 0:2])
print(y)
print(type(y))

[[ 5  6]
 [ 9 10]]
<class 'numpy.ndarray'>


In [ ]:
print(x[1,0],y[0,0])

5 5


In [ ]:
y[0,0]=55
print(x)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[55  6]
 [ 9 10]]


In [ ]:
row_1=x[1, :] #titik dua merepresentasikan  ambil seluruh nilai di baris

print(row_1)
print(row_1.ndim)
print(row_1.shape)

[5 6 7 8]
1
(4,)


In [ ]:
row_2=x[1:2, :]
print(row_2)
print(row_2.ndim)
print(row_2.shape)

[[5 6 7 8]]
2
(1, 4)


In [ ]:
h=np.array([[1,2],[3,4],[5,6]])
print(h)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(h[0,0])
print(h[1,1])
print(h[2,0])

print(np.array([[1,2],[3,4],[5,6]]))


1
4
5
[[1 2]
 [3 4]
 [5 6]]


##### indexing boleadn

In [ ]:
boolean_idx=(h>2)
print(boolean_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
m=h[h>2]
print(m)
print(m.ndim)
print(type(m))

[3 4 5 6]
1
<class 'numpy.ndarray'>


##### Numpy Math

In [ ]:
s=np.array([1,2])
print(s)
print(type(s)) #ngecek tipe data dari variable s
print(s.dtype) #ngecek tipe dari elemen2 yang ada di variable

[1 2]
<class 'numpy.ndarray'>
int64


In [ ]:
t=np.array([1,2.0])
print(t)
print(type(t)) #ngecek tipe data dari variable s
print(t.dtype) #ngecek tipe dari elemen2 yang ada di variable

[1. 2.]
<class 'numpy.ndarray'>
float64


In [ ]:
u=np.array([1.0,2,3.6],dtype=np.int64)
print(u)
print(type(u)) #ngecek tipe data dari variable s
print(u.dtype) #ngecek tipe dari elemen2 yang ada di variable

[1 2 3]
<class 'numpy.ndarray'>
int64


In [ ]:
x1=np.array([[1,2],[3,4]],dtype=np.float64)
y1=np.array([[5,5],[7,6]],dtype=np.float64)
print(x1)
print(y1)


[[1. 2.]
 [3. 4.]]
[[5. 5.]
 [7. 6.]]


In [ ]:
# penjumlahan
print(x1+y1)
print(np.add(x1,y1))

[[ 6.  7.]
 [10. 10.]]
[[ 6.  7.]
 [10. 10.]]


In [ ]:
#pengurangan
print(x1-y1)
print(np.subtract(x1,y1))


[[-4. -3.]
 [-4. -2.]]
[[-4. -3.]
 [-4. -2.]]


In [ ]:
#perkalian
print(x1)
print(y1)
print(x1*y1)

[[1. 2.]
 [3. 4.]]
[[5. 5.]
 [7. 6.]]
[[ 5. 10.]
 [21. 24.]]


In [ ]:
print(np.dot(x1,y1))

[[19. 17.]
 [43. 39.]]


In [ ]:
#akar
print(np.sqrt(x1))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.array(x1**2))
print(np.dot(x1,x1))

[[ 1.  4.]
 [ 9. 16.]]
[[ 7. 10.]
 [15. 22.]]


#Day 9


##lest Practic

###Pandas


**Create Data** - We begin by creating our own data set for analysis. This prevents the end user reading this tutorial from having to download any files to replicate the results below. We will export this data set to a text file so that you can get some experience pulling data from a text file
**Get Data** - We will learn how to read in the text file. The data consist of baby names and the number of baby names born in the year 1880.  
**Prepare Data** - Here we will simply take a look at the data and make sure it is clean. By clean I mean we will take a look inside the contents of the text file and look for any anomalities. These can include missing data, inconsistencies in the data, or any other data that seems out of place. If any are found we will then have to make decisions on what to do with these records.
**Analyze Data** - We will simply find the most popular name in a specific year.  
**Present Data** - Through tabular data and a graph, clearly show the end user what is the most popular name in a specific year.

In [ ]:
import pandas as pd

In [ ]:
#membuat data berupa banyak penggunaan sebuah nama di indonesia

nama = ['putra','gema','nusa','bangsa','negara','indonesia']
jumlah_nama = [998,756,531, 870, 349, 211]

In [ ]:
dataset=list(zip(nama,jumlah_nama)) #memasangkan 2 variable list
print(dataset)

[('putra', 998), ('gema', 756), ('nusa', 531), ('bangsa', 870), ('negara', 349), ('indonesia', 211)]


In [ ]:
data = pd.DataFrame(data= dataset, columns=['nama','jumlah_nama'])
data

nama  jumlah_nama
0      putra          998
1       gema          756
2       nusa          531
3     bangsa          870
4     negara          349
5  indonesia          211

In [ ]:
data.to_csv('sample_data.csv',index = False,header=False)

In [ ]:
from google.colab import files
files.download('sample_data.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#### Get data


Link if you want to read more about getting data in google colaboratory: https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92

In [ ]:
import os

# Tentukan nama direktori yang ingin Anda buat
nama_direktori = 'content/drive'

# Buat direktori
os.makedirs(nama_direktori, exist_ok=True)


In [ ]:
from google.colab import drive
drive.mount('content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
#mengubah directory
%cd /content/content/drive/MyDrive/content/drive/

In [ ]:
count_nama = pd.read_csv(r'sample_data.csv')
count_nama

In [ ]:
import os

# Mengubah direktori
os.chdir('/content/content/drive/MyDrive/content/drive/')

# Membaca file CSV
count_nama = pd.read_csv('sample_data.csv')
count_nama

In [ ]:
count_nama = pd.read_csv(r'sample_data.csv',header=None)
count_nama


In [ ]:
count_nama = pd.read_csv(r'sample_data.csv',header=None,names=['nama','jumlah_nama'])
count_nama

####Prepare data

In [ ]:
#Cek sumary
count_nama.info()

In [ ]:
# cek tipe data untuk setiap kolom
count_nama.dtypes

In [ ]:
#cek tipe data untuk spesifik kolom
count_nama.jumlah_nama.dtypes

In [ ]:
#cek ordo
count_nama.shape

In [ ]:
#cek statistik sumary untuk kolom bertipe numerik
count_nama.describe()

##### Analyze Data

In [ ]:
#Melihat 3 nama dengan jumlah terbanyak
urutan=count_nama.sort_values(['jumlah_nama'],ascending=False)
urutan.head(3)

In [ ]:
count_nama['jumlah_nama'].plot.bar()

##### Present Data


In [ ]:
# General syntax to import a library but no functions:
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
# Create graph
count_nama['jumlah_nama'].plot.bar()

# Maximum value in the data set
MaxValue = count_nama['jumlah_nama'].max()

# Name associated with the maximum value
MaxName = count_nama['nama'][count_nama['jumlah_nama'] == count_nama['jumlah_nama'].max()].values

# Text to display on graph
Text = str(MaxValue) + " - " + MaxName

# Add text to graph
plt.annotate(Text, xy=(1, MaxValue), xytext=(8, 0),
                   xycoords=('axes fraction', 'data'), textcoords='offset points')

# Materi Tambahan

##Objective 1 - A/B Testing

A/B testing allows individuals, teams and companies to make careful changes to their user experiences while collecting data on the impact it makes. This allows them to construct hypotheses and to learn what elements and optimizations of their experiences impact user behavior the most.

### Background

An online news portal aims to expand its business by acquiring new subscribers. Every visitor to the website takes certain actions based on their interest. **The company plans to analyze these interests and wants to determine whether a new feature will be effective or not**.

100 users are divided equally into two groups. The old landing page is served to the first group (control group) and the new landing page is served to the second group (treatment group).

Various data about the customers in both groups are collected in 'abtest.csv'.

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import seaborn as sns
sns.set(color_codes=True)
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.stats as stats

### Data Dictionary

* user_id - This represents the user ID of the person visiting the website.
* group - This represents whether the user belongs to the first group (control) or the second group (treatment).
* landing_page - This represents whether the landing page is new or old.
* time_spent_on_the_page - This represents the time (in minutes) spent by the user on the landing page.
* converted - This represents whether the user gets converted to a subscriber of the news portal or not.
* language_preferred - This represents the language chosen by the user to view the landing page.

In [ ]:
import os

# Tentukan nama direktori yang ingin Anda buat
nama_direktori = 'content/drive'

# Buat direktori
os.makedirs(nama_direktori, exist_ok=True)

In [ ]:
from google.colab import drive
drive.mount('content/drive')

In [ ]:
#mengubah directory
%cd /content/content/drive/MyDrive/content/drive/

In [ ]:
data = pd.read_csv('abtest.csv')
data

### Exploratory Data Analysis

Explore the dataset and extract insights using Exploratory Data Analysis :
1. How many variables and records of the dataset?
2. Is there a variable that has a blank record? if so, which variables and how many?
3. Group the variable into the type of data
4. Total & average time spent on the old landing page
5. Total & average time spent on the new landing page
6. What is the distribution of time spent on the landing page for each landing_page. which on is better?
7. % change in conversion for new landing page vs. old landing based on user language_preferred. what do you find?

**Please answer the task using python code and the result using text sel**

####Nomor 1


```
How many variables and records of the dataset?
```



In [ ]:
num_variables = len(data.columns)
num_records = len(data)
print("Number of variables:", num_variables)
print("Number of records:", num_records)

####Nomor 2


```
Is there a variable that has a blank record? if so, which variables and how many?
```



In [ ]:
print(data.isnull().sum())

####Nomor 3


```
Group the variable into the type of data
```



In [ ]:
data.dtypes

####Nomor 4


```
Total & average time spent on the old landing page
```



In [ ]:
data_old = data[ data["landing_page"] == "old" ]

Total_old = str(round(data_old["time_spent_on_the_page"].sum(), 2))
Mean_old = str(round(data_old["time_spent_on_the_page"].mean(), 2))

print("Total & average time spent on the old landing page across 50 users (control group): ", \
      Total_old+ " mins and", \
      Mean_old+ " mins.")

####Nomor 5


```
Total & average time spent on the new landing page
```



In [ ]:
data_new = data[ data["landing_page"] == "new"]

Total_new = str(round(data_new["time_spent_on_the_page"].sum(), 2))
Mean_new = str(round(data_new["time_spent_on_the_page"].mean(), 2))

print("Total & average time spent on the new landing page across 50 users (treatment group): ", \
      Total_new+ " mins and", \
      Mean_new+ " mins.")

####Nomor 6


```
What is the distribution of time spent on the landing page for each landing_page. which on is better?
```



In [ ]:
fig,ax = plt.subplots(1,3, figsize=(20,5))

sns.histplot(data["time_spent_on_the_page"], ax=ax[0], kde = True);
ax[0].set_ylim((0,25))
ax[0].axvline(data["time_spent_on_the_page"].mean(), c = "r")
ax[0].set_title("Time spent on either the old or new landing page")

sns.histplot(data_old["time_spent_on_the_page"], ax=ax[1], kde = True);
ax[1].set_ylim((0,25))
ax[1].axvline(data_old["time_spent_on_the_page"].mean(), c = "r")
ax[1].set_title("Time spent on the old landing page")

sns.histplot(data_new["time_spent_on_the_page"], ax=ax[2], kde = True);
ax[2].set_ylim((0,25))
ax[2].axvline(data_new["time_spent_on_the_page"].mean(), c = "r")
ax[2].set_title("Time spent on the new landing page")
plt.show()

####Nomor 7


```
% change in conversion for new landing page vs. old landing based on user language_preferred. what do you find?
```



In [ ]:
sns.countplot(x="converted", data=data, hue="landing_page");
plt.show()

print("% converted - old landing page: ", \
      str((data_old[data["converted"]=="yes"].count()["group"]/50)*100)+"%" )

print("% converted - new landing page: ", \
      str((data_new[data["converted"]=="yes"].count()["group"]/50)*100)+"%" )

In [ ]:
fig,ax = plt.subplots(1,3, figsize=(20,7))

sns.countplot(x="language_preferred", data=data.sort_values("language_preferred", ascending = True), \
              hue="converted", ax=ax[0]);
ax[0].set_ylim((0,25))
ax[0].set_title("Conversion rate")

sns.countplot(x="language_preferred", data=data_old.sort_values("language_preferred", ascending = True), \
              hue="converted", ax=ax[1]);
ax[1].set_ylim((0,25))
ax[1].set_title("Conversion rate - old landing page")

sns.countplot(x="language_preferred", data=data_new.sort_values("language_preferred", ascending = True), \
              hue="converted", ax=ax[2]);
ax[2].set_ylim((0,25))
ax[2].set_title("Conversion rate - new landing page")

plt.show()

In [ ]:
print("Number of users that prefer English, French and Spanish in the dataset are",  \
      str(data.groupby("language_preferred").count()["user_id"]["English"])+",", \
      str(data.groupby("language_preferred").count()["user_id"]["French"])+", and", \
      str(data.groupby("language_preferred").count()["user_id"]["Spanish"])+"." +"\n")

In [ ]:
data_new_converted = data_new[data["converted"]=="yes"]
data_old_converted = data_old[data["converted"]=="yes"]

print("% change in converted - new landing page vs old landing page:")

print(round(100*(data_new_converted.groupby("language_preferred").count()["user_id"] \
    - data_old_converted.groupby("language_preferred").count()["user_id"])/data_new_converted.groupby \
("language_preferred").count()["user_id"], 2))

* There are approximately equal number of English, French and Spanish preferring users (32, 34 and 34) in the dataset.
* % change in conversion for new landing page vs. old landing page is -10% for english. This means users that prefer English, converted marginally more when on the older landing page.
* % change in conversion for new landing page vs. old is 75% for French and 36.36% for Spanish. Users that prefer these languages, hence, converted more when on the new landing page. Conversion on the new landing page is very strong among users prefering French.

##Objective 2

### No 1 - Do the users spend more time on the new landing page than the old landing page?

* H0 : Null Hypothesis - The mean time spent on the new landing page is the same as the mean time spent on the old landing page.
* H1 : Alternate Hypothesis - The mean time spent on the new landing page is higher than the mean time spent on the old landing page.
Let μ1 and μ2 be the mean times spent on the new and old landing pages.

H0 : μ1 = μ2
H1 : μ1 > μ2

level of significance = 5%

In [ ]:
μ1, μ2 = data_new["time_spent_on_the_page"].mean() , data_old["time_spent_on_the_page"].mean()
std1, std2 = data_new["time_spent_on_the_page"].std() , data_old["time_spent_on_the_page"].std()
print("μ1, μ2, std1, std2:", str(round(μ1,2))+",", str(round(μ2,2))+",", str(round(std1,2))+","\
      , str(round(std2,2))+".")

* Continuous data - Yes, the time spent on landing pages is measured on a continuous scale.
* Normally distributed populations - Looking at the histogram probability density curves, as well as considering larger sample sizes of 50 (>i.e., 30), normal distribution assumption holds.
* Independent populations - As we are taking random samples from population for two different groups, the two samples are assumed to be independent.
* Unequal population standard deviations - As the sample standard deviations are different, the population standard deviations may be assumed to be different.


Two Independent Sample T-test for Equality of Means - Unequal Std Dev

In [ ]:
from scipy.stats import ttest_ind

test_stat, p_value = ttest_ind(data_new["time_spent_on_the_page"], data_old["time_spent_on_the_page"], \
                     equal_var = False, alternative = 'greater')
print('The p-value is ', p_value)

Insight:
* As the p-value (~0.00014) is less than the level of significance(0.05), we can reject the null hypothesis. Hence, we do have enough evidence to support the claim that mean time spent on the new landing page is higher than mean time spent on the old landing page.

###No 2 -  Is the conversion rate (the proportion of users who visit the landing page and get converted) for the new page greater than the conversion rate for the old page?

* H0 : Null Hypothesis - The conversion rate (the proportion of users who visit the landing page and get converted) for the new page is the same as the conversion rate for the old page.
* H1 : Alternate Hypothesis - The conversion rate for the new page is greater than the conversion rate for the old page.

Let p1 and p2 be the conversion rates for the new and old landing pages.

* H0 : p1 = p2
* H1 : p1 > p2


level of significance = 5%

The formulated hypotheses are concerned with proportions. A test of proportions can be used to analyse the hypotheses and draw a conclusion. We shall use a Proportions Z test for this problem.

In [ ]:
convertedn_new = float(data_new[data["converted"]=="yes"].count()["group"])
p1 = float(round(convertedn_new/50, 2))
convertedn_old = float(data_old[data["converted"]=="yes"].count()["group"])
p2 = float(round(convertedn_old/50, 2))

print(f'The conversion rates for new landing page and old landing page are {p1} and {p2} respectively.')

The proportions in the sample are larger for the new landing page. Let's conduct the test to see if this is significant

Two Proportion Z-test

In [ ]:
from statsmodels.stats.proportion import proportions_ztest
stat, pval = proportions_ztest([convertedn_new, convertedn_old], [50, 50], alternative = 'larger')

print('The p-value is '+ str(pval))

Insight:
* As the p-value (~0.008) is less than the level of significance (0.05), we can reject the null hypothesis. Hence, we do have enough evidence to support the claim that conversion rate for the new landing page is higher than conversion rate for the old landing page.

##Summary

**Exploratory Data Analysis**
* Total (across all users) and average time spent on the new landing page (311.16 & 6.22 mins) is higher than on the old landing page (226.62 & 4.53 mins).
* % conversion rate is higher for new landing page (66%) when compared to old landing page (42%).
* There are apporximately equal number of English, French and Spanish preferring users (32, 34 and 34) in the dataset. % change in conversion for new landing page vs. old landing page is -10% for English, 75% for French and 36.36% for Spanish. Conversion when on the new landing page is very strong among users prefering French and marginally poor for users prefering English.

**Statistical Analysis**

* We statistically found enough evidence to support the claim that mean time spent on the new landing page is higher than mean time spent on the old landing page using a two independent sample T-test for equality of means - unequal std dev.
* We statistically found enough evidence to support the claim that conversion rate for the new landing page is higher than conversion rate for the old landing page using a two proportion Z-test.